### ISSUE TITLE
Exposed Testing  End-point 

### ISSUE THREAD

**Issue by debianchef** [rhutmann/react-korba-payment#7]
## Impact
There is an exposed  internal testing endpoint  in  `README.MD`  

`https://paywithkorba.s3-eu-west-1.amazonaws.com/test-checkout.js`

`https://testxchange.korba365.com/api/v1.0/website_checkout/`

## Recommendation 

Use an isolated  domain for testing

**Comment by eben92** [comment]
> ## Impact
> 
> There is an exposed  internal testing endpoint  in  `README.MD`  
> 
> 
> 
> `https://paywithkorba.s3-eu-west-1.amazonaws.com/test-checkout.js`
> 
> 
> 
> `https://testxchange.korba365.com/api/v1.0/website_checkout/`
> 
> 
> 
> 
> 
> 
> 
> ## Recommendation 
> 
> 
> 
> Use an isolated  domain for testing 

Resolved!. Thanks
Closing this now.
Kindly reopen if the updated domain is not an isolated domain for testing
